### ISSUE TITLE
Move all util functions to Tithiwa class or do something else if possible

### ISSUE THREAD

**Issue by Maskgirl** [Tithibots/tithiwa#16]
I noticed we need to pass the `browser` variable to util functions, so I believe its better if we add those functions inside the `Tithiwa` class or something else so those functions should have direct access to the `browser` variable.

We can make that start with `_` underscore because a variable or method starting with a single underscore is intended for internal use.

**Comment by NavpreetDevpuri** [comment]
I think we need to use inheritance here.
