### ISSUE TITLE
Regain the flexibility of the module. Also add non-class functions to automate

### ISSUE THREAD

**Issue by Maskgirl** [Tithibots/tithiwa#18]
I feel by https://github.com/Tithibots/tithiwa/pull/17
We removed the flexibility
before that, we can send any selenium drive to the functions like 
```python 
memberlist = tithiwabot.group.scrape_members_from_group("PROGRAMMING", browser=any)
```
I think we should add separate functions, that can automate any selenium driver by just taking an argument for that. 
Maybe create a file `functions.py` or something

**Comment by NavpreetDevpuri** [comment]
I also felt that. 
Let me try that.
