### ISSUE TITLE
Make function remove_members_from_group() in Group class for removing given members from whatsapp group.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#22]
Automate removing given member from a given group. 
See this two [functions](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/group.py#L54-L84)

Just use `_open_group_members_list()` to open list of group members as did in function `make_group_admins()`
Then just copy and make some changes to that function ` make_group_admins()` to make `remove_members_from_group()`

**Comment by willidert** [comment]
Leave it to me, I have some experiences with selenium and bots for whatsapp. In return can you help me complete the hacktoberfest challenge? It is a personal achievement for me.
