### ISSUE TITLE
Create GUI having some buttons and input boxes.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#31]
I suggest looking at [TK](https://www.geeksforgeeks.org/python-gui-tkinter/)
Create some basic GUI for example having an input to ask mobile number and enter a message then a button to send a message

**Comment by willidert** [comment]
Hello @NavpreetDevpuri , i'm trying this, i will try harder.
I need to assemble the screen and connect with the robot's `send_message_to_number` function. For this issue, is there anything else or did I understand you correctly?

**Comment by NavpreetDevpuri** [comment]
@willidert 
look at this [example](https://github.com/Tithibots/tithiwa/pull/15#issue-501191716), we are calling functions to perform automation 

And we just need some kind of GUI, as we added in `gui.py`, it is not working but you can have a basic idea after looking into it. 
That GUI is gona have all options that our bot can do and we just need to give some inputs and click on some buttons to perform automations. 

something like `on click to some button` then `call that function with inputs to perform automation`

Just like you did while commenting on this issue, you just clicked on the `comment` button and all backend things are handled by that GUI website.
