### ISSUE TITLE
Somehow get the default module directory path and assign that to sessiondir variable as default value 

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#32]
look at this [line](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/session.py#L14-L15) it seems incorrect because if the user change folder name then it will create problems.

And add the content `SESSIONDIR=something` to `constants.py` and use it.

**Comment by willidert** [comment]
Can i use os for this issue? Something like this:
`SESSIONDIR=current_local + session_dir`
`current` would be `os.getcwd()` + `os.path.join()` and `session_dir` is in the same diretory as the `tithiwa.py` and the other scripts, sure?

**Comment by NavpreetDevpuri** [comment]
`os.getcwd()` can be changed and this may create problems in future. 
```python 
# Now create a new directory
os.mkdir('NewDirectory')
# Change the working directory to the newly created directory
os.chdir('NewDirectory')
# Print the current working directory
print("Current working directory after changing it:")
print(os.getcwd())
```
