### ISSUE TITLE
Add __all__ to python files. 

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#33]
See [this](https://stackoverflow.com/a/64130/8099521)
for example for `session.py` it should be because we only have one class in that file 
```python 
__all__ = ["Session"]

from util import *
from constants import SELECTORS
from waobject import WaObject
```

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. Could you please assign it to me? Also if I am understanding this correctly I have to add `__all__` to python which only have one class in it, right?

**Comment by NavpreetDevpuri** [comment]
@pret3nti0u5 add this to all files even they have multiple files for example `flextithiwa.py` is having 3 classes so add those three classes to `__all__` list to that file.

**Comment by pret3nti0u5** [comment]
Opened a PR #36. Let me know if any further edits are needed.
