### ISSUE TITLE
Create send_message_with_mention_all_to_group() to send given message to a group mentioning all members

### ISSUE THREAD

**Issue by Maskgirl** [Tithibots/tithiwa#34]
add `send_message_with_mention_all_to_group(self, groupname, message)` to class Group 

![ShareX_pOaJ6FayL8](https://user-images.githubusercontent.com/50572161/95853791-9bba2580-0d73-11eb-838e-c868402bf542.png)

**Comment by Vipul-Bajaj** [comment]
Can I work on this?

**Comment by NavpreetDevpuri** [comment]
@Vipul-Bajaj sure. 
Welcome.
