### ISSUE TITLE
Create exit_from_all_groups() in Group class

### ISSUE THREAD

**Issue by Maskgirl** [Tithibots/tithiwa#35]
Automate as follow or try something else 
1. go through all chats by using the DOWN arrow key because in HTML all chats are un-ordered 
2. determine someway that the currently active element on the browser is a group. [browser.switch_to.active_element](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/group.py#L61)
3. then if its a group then just automate `Exit group` for that group 

![ShareX_eF8QbUDkha](https://user-images.githubusercontent.com/50572161/95855074-79c1a280-0d75-11eb-90c5-e03b1b19d482.png)

**Comment by Vipul-Bajaj** [comment]
I can work on this

**Comment by Vipul-Bajaj** [comment]
Sorry, Can u assign this to someone else, got busy somewhere else
