### ISSUE TITLE
Create settings.py having Settings class for changing web WhatsApp's settings

### ISSUE THREAD

**Issue by Maskgirl** [Tithibots/tithiwa#39]
Add the following automation
1. `notifications(is_sounds, is_desktop_alerts, is_show_previews, is_turn_off_desktop_notifications):` taking boolean values to set followings 
![chrome_QNGpHqboBl](https://user-images.githubusercontent.com/50572161/95900218-32580800-0daf-11eb-8a3d-b201af014c16.png)

2. `theme(theme):` Taking constant values from contants.py i.e add new class `STRINGS` having sub-class `SETTINGS` having contants like `THEME_LIGHT='Light'` so that we can use `theme(STRINGS.SETTINGS.THEME_LIGHT)`
![chrome_nBXgRErEzJ](https://user-images.githubusercontent.com/50572161/95900538-aeeae680-0daf-11eb-9b41-7a7c681dfcd3.png)

3. `block_contacts(contacts):` takes a list of contacts to add in the blocklist
![chrome_Tho1Z9WUQC](https://user-images.githubusercontent.com/50572161/95900650-d641b380-0daf-11eb-92d1-a042038f0399.png)

**Comment by beatorizu** [comment]
Hey, I would like to try this issue

**Comment by Maskgirl** [comment]
> Hey, I would like to try this issue

@beatorizu You are most welcome. 😊

**Comment by NavpreetDevpuri** [comment]
@beatorizu 
I want to suggest something that will help alot
https://github.com/Tithibots/tithiwa/pull/30#issuecomment-707633120 and https://github.com/Tithibots/tithiwa/pull/30#issuecomment-707644654

**Comment by NavpreetDevpuri** [comment]
@beatorizu you can ask me if you are facing any problems while doing it.

**Comment by beatorizu** [comment]
Thank you, guys 😊

**Comment by beatorizu** [comment]
How do I start a session? Do I need to use my personal number?

**Comment by NavpreetDevpuri** [comment]
> How do I start a session? Do I need to use my personal number?

You can use it, but as i know it a bad idea to use my personal number as i was experimenting things like exiting groups.. Etc so i cloned my whatsapp and created a new whatsapp with my other number for that purpose.

**Comment by NavpreetDevpuri** [comment]
> How do I start a session? Do I need to use my personal number?

You can use it, but as I know it is a bad idea to use my personal number as I was experimenting with things like exiting groups. Etc so I cloned my WhatsApp app on my mobile and created a new WhatsApp account with my other mobile number for that purpose.

**Comment by beatorizu** [comment]
> > How do I start a session? Do I need to use my personal number?
> 
> You can use it, but as I know it is a bad idea to use my personal number as I was experimenting with things like exiting groups. Etc so I cloned my WhatsApp app on my mobile and created a new WhatsApp account with my other mobile number for that purpose.

As I am changing things related to settings I believe that it is fine to use my own phone number :thinking:

**Comment by NavpreetDevpuri** [comment]
> As I am changing things related to settings I believe that it is fine to use my own phone number 🤔
Yes.
