### ISSUE TITLE
Create remove_group_admins() in Group class Similar to make_group_admins()

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#48]
Take a look at https://github.com/Tithibots/tithiwa/blob/7cef0e13b6ab6f8050060bb3cbaad0f59f79c19e/tithiwa/group.py#L50
Just need to click on the `Remove` button forgiven members

**Comment by Muskan33** [comment]
Hey, can you please assign this issue to me? I have prior experience with selenium.

**Comment by NavpreetDevpuri** [comment]
Good luck!

**Comment by pyvelkov** [comment]
Hey @NavpreetDevpuri Can I take this issue as it has not been solved yet? I will make a PR soon.

**Comment by NavpreetDevpuri** [comment]
@pyvelkov good luck!
