### ISSUE TITLE
Create open_chat_to_myself() in contact.py 

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#55]
First, need to do https://github.com/Tithibots/tithiwa/issues/54 
then just use [open_chat_by_number_using_url(number)](https://github.com/Tithibots/tithiwa/blob/49f13756a54777478c2c57d2166d8cff24bf5d4a/tithiwa/contact.py#L18) to open chatroom

**Comment by immanuelsavio** [comment]
Can you assign this issue to me
