### ISSUE TITLE
Create join_groups() in group.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#56]
firstly need to do https://github.com/Tithibots/tithiwa/issues/55
Then just send all given group links to the chatroom and just click on those groups it will promote to join and just click on button join as similar to https://github.com/Tithibots/tithiwa/issues/53

![ShareX_pEDnAknmrz](https://user-images.githubusercontent.com/30471072/96604064-4dc49500-1312-11eb-8809-c9c899ff3259.png)

**Comment by immanuelsavio** [comment]
If this is still open can you assign this to me?

**Comment by NavpreetDevpuri** [comment]
@immanuelsavio you are welcome
I am assigning u https://github.com/Tithibots/tithiwa/issues/57
It will a little challenging, and that's what makes it fun
Let me know if u face any kind of problem 
Good luck!

**Comment by immanuelsavio** [comment]
Haha, Im new to selenium with python but yeah I'll give it a go 😉

**Comment by NavpreetDevpuri** [comment]
I am unable to assign u the other 3 issues. because u had not commented on those issues. 
please comment also on those 3 other issues. 

😊

**Comment by immanuelsavio** [comment]
Sure, will do
