### ISSUE TITLE
Solve 4 good first issues 

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#57]
Solve 
https://github.com/Tithibots/tithiwa/issues/53
https://github.com/Tithibots/tithiwa/issues/54
https://github.com/Tithibots/tithiwa/issues/55
https://github.com/Tithibots/tithiwa/issues/56

**Comment by immanuelsavio** [comment]
Can you assign this to me

**Comment by immanuelsavio** [comment]
Can you assign the remaining 3 to me
