### ISSUE TITLE
Create send_a_message_to_multiple_chats() in chatroom.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#58]
`send_a_message_to_multiple_chats(names, message)`: taking list `names` and string `message`
just loop through list `names` and then use function [send_message_to_name_or_number(name, message)](https://github.com/Tithibots/tithiwa/blob/bf817e97b134ce682d464767426f0f293e307017/tithiwa/chatroom.py#L23)

**Comment by mickm3n** [comment]
I can help with this

**Comment by NavpreetDevpuri** [comment]
You are welcome!

**Comment by NavpreetDevpuri** [comment]
good luck!
