### ISSUE TITLE
Create get_number_from_contact_name() in contact.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#60]
do as follow 
1. use [open_chat_by_number(name)](https://github.com/Tithibots/tithiwa/blob/7cef0e13b6ab6f8050060bb3cbaad0f59f79c19e/tithiwa/contact.py#L12) to open chat 
2. use [_open_chat_info()](https://github.com/Tithibots/tithiwa/blob/a278e4a27af13a8469262ff28328ca74135441eb/tithiwa/chatroom.py#L33-L37) to open chatroom info
<img src="https://user-images.githubusercontent.com/30471072/96708887-810d2f80-13b7-11eb-8657-bb6ccaa7db21.png" alt="drawing" width="500"/>

3. scape mobile number 
4. use [_close_chat_info()](https://github.com/Tithibots/tithiwa/blob/a278e4a27af13a8469262ff28328ca74135441eb/tithiwa/chatroom.py#L36) to close chatroom info
5. return scrapped number and Done

**Comment by NavpreetDevpuri** [comment]
You also try to find the mobile number as follows by somehow getting the network request. When we open chat to someone a request is sent to through the browser and we can somehow get that request in python 
![ShareX_9eT3WGnXFZ](https://user-images.githubusercontent.com/30471072/96863222-28f02f00-1484-11eb-8d04-7ad3bf15a962.png)

**Comment by pyvelkov** [comment]
Hello, 
I have done this without asking you to assign. (I forgot sorry)
I will link a PR to this soon.

**Comment by NavpreetDevpuri** [comment]
> I have done this without asking you to assign. (I forgot sorry)

No problem 🤗

Well done!
