### ISSUE TITLE
Create delete_chats_of_all_contacts() in contacts.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#62]
do as follow 
1. go through all contacts chats same as in [exit_from_all_groups()](https://github.com/Tithibots/tithiwa/blob/a278e4a27af13a8469262ff28328ca74135441eb/tithiwa/group.py#L114) 
NOTE: by using [CONTACTS__NAME_IN_CHATS ](https://github.com/Tithibots/tithiwa/blob/0ba6306873121bd3b87e9a53cae780c474586672/tithiwa/constants.py#L29) you can get all chats of contacts.
2. open chat options by using [CHATROOM__OPTIONS](https://github.com/Tithibots/tithiwa/blob/c44c381913171a1b5528b59c598dd679e38b62b0/tithiwa/constants.py#L28)
3. press on `Delete chat` and wait for the chat to be deleted by using [self._close_info()](https://github.com/Tithibots/tithiwa/blob/c44c381913171a1b5528b59c598dd679e38b62b0/tithiwa/waobject.py#L21)
![ShareX_3wxkCm3ZmW](https://user-images.githubusercontent.com/30471072/96861958-78356000-1482-11eb-8a4f-0f0ff8e57cfc.png)

**Comment by pyvelkov** [comment]
can I work on this? I will submit PR soon
