### ISSUE TITLE
Create get_my_name() in waobject.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#67]
for given example it should return "NavpreetDevpuri"
![chrome_4anjNsew1Y](https://user-images.githubusercontent.com/30471072/97092627-1ed85700-1663-11eb-8b67-f1afa6ce93d2.png)

**Comment by ZarghamDanial** [comment]
Hey, can you assign this to me?

**Comment by NavpreetDevpuri** [comment]
@ZarghamDanial Welcome

**Comment by NavpreetDevpuri** [comment]
Good luck!

**Comment by ZarghamDanial** [comment]
@NavpreetDevpuri I have created the function to get the name of the user

**Comment by ZarghamDanial** [comment]
@NavpreetDevpuri please accept the pr before Hacktoberfest ends 😄

**Comment by ZarghamDanial** [comment]
Hey @NavpreetDevpuri , I am seeing "Ineligible repo" on my hacktoberfest profile for this pr. Can you tell me what could have happened?

**Comment by NavpreetDevpuri** [comment]
I am sorry. I thought hackoctoberfest is over. So i removed labels from repo. But i again added those labels.

**Comment by ZarghamDanial** [comment]
There is a window of 15 days or review after merging the pr. Only after those 15 days, the merging is said to be successful in Hacktoberfest. My pr is still showing:

"Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR."

Can you once check if you added it back properly please? Thanks!

**Comment by NavpreetDevpuri** [comment]
understood..... I added only `hacktoberfest-accepted` and forgot to add `hacktoberfest` thanks o remind me

**Comment by ZarghamDanial** [comment]
Hi @NavpreetDevpuri for some reason, the pr at hacktoberfest is still showing the same issue. I am not sure how to resolve it. Can you see if everything's okay for this merging
