### ISSUE TITLE
Create get_my_about() in waobject.py

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#68]
forgiven example, it should return "ਮਨ ਨੀਵਾਂ ਮੱਤ ਉੱਚੀ।"
![chrome_4anjNsew1Y](https://user-images.githubusercontent.com/30471072/97092627-1ed85700-1663-11eb-8b67-f1afa6ce93d2.png)

**Comment by beatorizu** [comment]
@NavpreetDevpuri  I would like to try this issue

**Comment by NavpreetDevpuri** [comment]
good luck!

**Comment by NavpreetDevpuri** [comment]
Clear those before working on it because it will create conflicts in PR, check [this](https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind/41289258) or you can simply delete the forked repo and again fork it 
![chrome_JhmLt27KR1](https://user-images.githubusercontent.com/30471072/97776184-0947bd80-1b8c-11eb-8fbb-eafb75d8372b.png)

**Comment by beatorizu** [comment]
Thank you! :grinning:

**Comment by beatorizu** [comment]
Is a close method necessary?

**Comment by NavpreetDevpuri** [comment]
> Is a close method necessary?
you can use `BACK_BUTTON = (By.CSS_SELECTOR, '.t4a8o')` to press backbutton

**Comment by NavpreetDevpuri** [comment]
@beatorizu check that I just created 
https://github.com/Tithibots/tithiwa/blob/1f29ec97225c41b137545ac76c608c2e52d295a3/tithiwa/waobject.py#L152-L153
