### ISSUE TITLE
All my PRs on this Repo were not accepted by hacktoberfest

### ISSUE THREAD

**Issue by pyvelkov** [Tithibots/tithiwa#73]
All my PRs on this Repo were not accepted by hacktoberfest.
This repo was in hacktoberfest but I'm guessing the maintainer opted out last day? Why is that?

**Comment by NavpreetDevpuri** [comment]
I removed those labels! 
I think hackoctoberfest is over. 
Shouldn't i? 

I will again add those labels

**Comment by pyvelkov** [comment]
Hey i figured that was the case. I emailed hacktoberfest sponsors to try and resolve the issue. Could you please add "hacktoberfest-accepted" to PRs made in october

**Comment by NavpreetDevpuri** [comment]
Added. 
Understood your 13 days timer is not finished yet.
